### ISSUE TITLE
usage getStatus and getStatuses functions

### ISSUE THREAD

**Issue by saitahmety** [node-escpos/driver#24]
I want to use getStatus function and when I call it as follows,
PrinterStatus and other classes not exported. 
So, `let  printerStatus = printer.getStatus(PrinterStatus);`  // class type can't work

this exports can be added
![image](https://user-images.githubusercontent.com/86234440/203824461-d7bcf0e9-e5f1-4551-a58d-a12f3ce53959.png)

or 
`let  printerStatus = printer.getStatus("PrinterStatus");`  // string type can't work
this code can be added
![image](https://user-images.githubusercontent.com/86234440/203824724-5f1f6985-fbe8-4a5c-a228-5f3a655a8904.png)

Or is there any other solution besides these ? How should I use getStatus() function ?

**Comment by saitahmety** [comment]
Moreover,
getStatuses function does not return response when at least one of these 4 statuses is undefined. 
Because of "if (buffer.length < 4)" condition.
![image](https://user-images.githubusercontent.com/86234440/203578418-1983b84c-3112-4e63-bd99-430d71eaf951.png)

But I want to get the other statuses even if the byte data of one status is undefined.
When I remove "if (buffer.length < 4)" condition
output like this,
![image](https://user-images.githubusercontent.com/86234440/203933866-7625a594-45cf-44cc-8442-ed5ca707a3d2.png)

Can we remove this condition ?

Please revision code and release NPM. It's important for my project.
Thanks for this awesome project.

**Comment by felipeguimaraes2** [comment]
@saitahmety the printer must return all four statuses in this method if the memory switch 1-3 is set to "receive buffer full" from "receive buffer full or offline", as you can see here https://github.com/mike42/escpos-php/issues/43#issuecomment-389453232

After changing this memory switch, it returns successfully. But there is still a bug because the promise is not rejected in this situation, so I created a pull https://github.com/node-escpos/driver/pull/46 to solve it

**Comment by saitahmety** [comment]
Oh I got it, thank you so much @felipeguimaraes2 , solved on this https://github.com/node-escpos/driver/pull/46
