### ISSUE TITLE
Can USB Adapter for check Paper is Out Event ?

### ISSUE THREAD

**Issue by YovanggaAnandhika** [node-escpos/driver#28]
i wish usb printer device detect printer device paper out. is visible ?

**Comment by dohooo** [comment]
What problem do you want to check? no page?

**Comment by YovanggaAnandhika** [comment]
get Information for USB Adapter Package Printer device is Paper out

**Comment by saitahmety** [comment]
you can use getStatus or getStatuses functions for get information for paper out, paper low etc. 

according to the incoming bit data, error message returns like this 
![Screenshot 2022-11-28 173102](https://user-images.githubusercontent.com/86234440/205440899-3d73160d-2ca4-4af4-a134-8c7c8e8b5fc3.png)

but in order to use these functions properly, we should look at this issue #24  and solve it.

**Comment by felipeguimaraes2** [comment]
Check out this comment @YovanggaAnandhika: https://github.com/node-escpos/driver/issues/24#issuecomment-1363985749
